UKHomeOffice/policy-admission

README.md, kube/registration.yml, pkg/authorize/authorize.go, pkg/authorize/domains/authorizer.go, pkg/authorize/domains/authorizer_test.go, pkg/authorize/domains/doc.go
- adding the ingress domains enforcer to here rather than separating in a different project
=> Ingress Domains

cmd/policy-admission/main.go
=> Release v0.0.4

cmd/policy-admission/main.go, pkg/api/doc.go, pkg/authorize/authorize.go, pkg/authorize/imagelist/authorizer.go, pkg/authorize/imagelist/authorizer_test.go, pkg/authorize/imagelist/doc.go, pkg/authorize/images/authorize.go
- adding the imagelist authorizer plugin
=> ImageList Authorizer

pkg/api/doc.go, pkg/authorize/authorize.go, pkg/authorize/denyloadbalancers/authorizer.go, pkg/authorize/denyloadbalancers/authorizer_test.go, pkg/authorize/denyloadbalancers/doc.go, pkg/server/admission.go
- adding a new authorizer allowing us to switch off support for Service type Loadbalancer
=> Deny Load Balancers

cmd/policy-admission/main.go
- releasing the v0.0.7
- adds the denyloadbalancers authorizer
=> Releace v0.0.7

pkg/authorize/authorize.go, pkg/authorize/services/authorizer.go, pkg/authorize/services/authorizer_test.go, pkg/authorize/services/doc.go
- removing the denyloadbalancer and adding a generic services authorizer instead
=> Service Authorizer

pkg/authorize/domains/authorizer.go, pkg/authorize/domains/authorizer_test.go, pkg/authorize/images/authorize.go, pkg/authorize/images/authorize_test.go, pkg/authorize/securitycontext/authorizer.go, pkg/authorize/securitycontext/authorizer_test.go, pkg/authorize/services/authorizer.go, pkg/authorize/services/authorizer_test.go, pkg/authorize/tolerations/authorizer.go, pkg/authorize/tolerations/authorizer_test.go, pkg/server/admission.go, pkg/server/misc_test.go, pkg/server/serve_test.go, pkg/utils/misc.go
- removing the forbidden field errors and using Invalid only
- providing more concise details at the exact errors
=> Error Details

pkg/api/doc.go, pkg/server/admission.go
- adding the providers to request that internal errors are ignored
=> Provider Skip Internal Errors

Makefile, cmd/policy-admission/main.go, glide.lock, glide.yaml, pkg/authorize/domains/authorizer.go, pkg/authorize/domains/authorizer_test.go, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/kubecertmanager/authorize_test.go, pkg/server/admission.go, pkg/server/doc.go, pkg/server/middleware.go
- Adding a logging middleware for debugging purposes
- Fixed up the decoding of the ingress resources by switching back to k8s.io/kubernetes api
=> Decoding Fixes

cmd/policy-admission/main.go, pkg/authorize/domains/authorizer.go, pkg/authorize/domains/authorizer_test.go
- fixing up the domains authorixer with multiple whitelists
- adding the unit test to validate the change
=> Domains Authorizer

cmd/policy-admission/main.go, glide.lock, glide.yaml, pkg/authorize/imagelist/authorizer.go, pkg/authorize/imagelist/metrics.go, pkg/authorize/metrics.go, pkg/authorize/wrapper.go, pkg/server/admission.go, pkg/server/admission_test.go, pkg/server/doc.go, pkg/server/metrics.go, pkg/server/metrics_test.go, pkg/server/misc.go, pkg/server/serve.go, pkg/utils/config.go, pkg/utils/metrics.go, pkg/utils/misc.go, pkg/utils/retry.go, pkg/utils/retry_test.go
- adding the metric instrumentation to the controller
=> Prometheus Metrics

.drone.yml, Makefile, pkg/authorize/imagelist/authorizer_test.go
- updating the golang version to v1.10
=> Go Version v1.10

Dockerfile, README.md, cmd/policy-admission/main.go
- Specify UID in Dockerfile user creation
- New version v0.0.13
=> Docker image UID for user, v0.0.13

cmd/policy-admission/main.go, pkg/authorize/securitycontext/authorizer.go, pkg/authorize/securitycontext/authorizer_test.go, pkg/authorize/securitycontext/doc.go
- permitting a namespace to bypass the subpath enforcement
=> Subpath Namespace Bypass

pkg/authorize/scripts/authorizer.go, pkg/authorize/scripts/authorizer_test.go
- fixing up the timeout on the script authorizer and adding a unit test
=> Script Timeout

pkg/api/doc.go, pkg/authorize/domains/authorizer.go, pkg/authorize/imagelist/authorizer.go, pkg/authorize/images/authorize.go, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/namespaces/authorizer.go, pkg/authorize/scripts/authorizer.go, pkg/authorize/services/authorizer.go, pkg/authorize/tolerations/authorizer.go, pkg/authorize/values/authorizer.go, pkg/authorize/wrapper.go
- adding a stop method to the authorizers
=> Stop Method

pkg/events/slack/slack.go
- updating the format of slack message
=> Slack Message Format

cmd/policy-admission/main.go, pkg/server/admission.go, pkg/server/admission_test.go, pkg/server/doc.go
- expose the rate limiting via a command line switch
=> Rate Limit

kube/deployment.yml, pkg/server/admission.go
- cleaning the admit logic, adding extra logging and handling the unsupported
=> - updating the deployment example

pkg/api/doc.go, pkg/events/events.go, pkg/events/events_test.go, pkg/events/kube/events.go, pkg/events/slack/slack.go, pkg/server/admission.go
- adding extra detail to the events interface
=> Extra Detail

Gopkg.lock, pkg/api/doc.go, pkg/server/handlers.go, pkg/server/informer.go, pkg/server/middleware.go, pkg/server/server.go, pkg/utils/misc.go, pkg/utils/misc_test.go
- switching to using an informer
=> Resource Informer 

pkg/events/events.go
- removing the object name from the event hash
=> Event Hash

cmd/policy-admission/main.go
- cutting a quick release with the event hash changed
=> Release v0.0.24

Gopkg.lock, Makefile
- updating the vendor lock file and adding a verbose to the Makefile
=> Dependencies

Gopkg.lock, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/kubecertmanager/authorize_test.go, pkg/authorize/kubecertmanager/doc.go, pkg/authorize/kubecertmanager/helpers.go
- adding the ability to pull the hosted domains from route53
=> Hosted Domains

cmd/policy-admission/main.go, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/kubecertmanager/doc.go
- using environment variable for the secrets rather than the config
=> - bumping the version to v0.0.29

cmd/policy-admission/main.go, pkg/api/doc.go, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/kubecertmanager/authorize_test.go, pkg/authorize/kubecertmanager/doc.go
- adding a dns check skipper for the kubecertmamager
=> DNS Check Skipper

Dockerfile, cmd/policy-admission/main.go, pkg/api/doc.go, pkg/authorize/scripts/authorizer.go, pkg/server/authorize.go
- the admission object does not contain the group kind, adding it for scripts
- updating to alpine:3.8
=> Group Kind

pkg/authorize/scripts/authorizer.go
- only inject the namespace if required
=> Namespace If Only

cmd/policy-admission/main.go
=> Cutting a Release

Makefile, cmd/policy-admission/main.go, pkg/api/doc.go, pkg/api/filter.go, pkg/api/filter_test.go, pkg/authorize/domains/authorizer.go, pkg/authorize/domains/doc.go, pkg/authorize/imagelist/authorizer.go, pkg/authorize/imagelist/doc.go, pkg/authorize/images/authorize.go, pkg/authorize/images/doc.go, pkg/authorize/kubecertmanager/authorize.go, pkg/authorize/kubecertmanager/doc.go, pkg/authorize/scripts/doc.go, pkg/authorize/services/authorizer.go, pkg/authorize/services/doc.go, pkg/authorize/tolerations/authorizer.go, pkg/authorize/tolerations/doc.go, pkg/authorize/values/authorizer.go, pkg/authorize/values/doc.go, pkg/server/authorize.go
- allowing us to ignore namespace by labels
=> Ignore By Label

cmd/policy-admission/main.go, pkg/authorize/domains/doc.go, pkg/authorize/images/doc.go, pkg/authorize/kubecertmanager/doc.go, pkg/authorize/scripts/doc.go, pkg/authorize/services/doc.go, pkg/authorize/tolerations/doc.go, pkg/authorize/values/doc.go
- fixing up the typos and making the field name consistent
=> Fixing Typos

.drone.yml, Dockerfile, Makefile
Additional changes:
- Build with go v1.12.8+ (patching CVE-2019-9512, CVE-2019-9514)
- Update image to alpine v3.10 (patching CVE-2019-14697)
=> Add anchore image scanning
